Updated code format of neovipe and added .editorconfig

diff --git a/nvipe b/nvipe
--- a/nvipe
+++ b/nvipe
@@ -38,10 +38,10 @@
 # SOFTWARE.
 # ------------------------------
 function usage() {
-	cat <<EOF
+  cat <<EOF
 Allows interaction with pipes via \$EDITOR by connecting it to stdin and stdout.
 
-Usage: $(basename "$0") [-t[=]TEMPLATE] [-p] [-h] [-v]
+Usage: $(basename "${0}") [-t[=]TEMPLATE] [-p] [-h] [-v]
 
 Options:
   -h, --help			Show this help message and exit.
@@ -51,15 +51,15 @@ Options:
 
 Example:
 	echo "change me" > "my_input.txt"
-	head -n 1 "my_input.txt" | cut -f 1 | $(basename "$0") > "my_output.txt"
+	head -n 1 "my_input.txt" | cut -f 1 | $(basename "${0}") > "my_output.txt"
 	cat "my_output.txt"
 	This text could be changed to anything you want.
 EOF
 }
 
 function version() {
-	cat <<EOF
-$(basename "$0") 0.1.2
+  cat <<EOF
+$(basename "${0}") 0.1.2
 Copyright © 2026 Josh Beale <jbeale2023@gmail.com>.
 Licence: The GNU General Public License v2.0
 Adapted from the work of Julian Gruber at https://github.com/juliangruber/vipe under the terms of the MIT License.
@@ -68,71 +68,71 @@ EOF
 }
 
 function main() {
-	template="${1}"
-	pipe_without_save="${2}"
-	if tmp=$(mktemp -q -p "${TMPDIR:-/tmp}" "$template"); then # Create a temp file to act as a buffer for $EDITOR with adequate randomness to avoid race condition attacks, using user template if provided
-		trap 'rm -rf "$tmp"' ERR EXIT HUP INT TERM                # Removes the temp file when execution finishes, except on receipt of SIGKILL
-		if [ ! -t 0 ]; then                                       # If connected to stdin, dump it to the temp file
-			cat >"$tmp"
-		fi
-		mtime=$(stat -c %Y "$tmp" 2>/dev/null || echo 0)                                                        # Tracks file mtime before $EDITOR is invoked
-		${VISUAL:-${EDITOR:-vi}} "$tmp" </dev/tty >/dev/tty || exit $?                                          # Invokes $EDITOR with stdio connected
-		if [ "$pipe_without_save" -eq 1 ] || [ "$mtime" != "$(stat -c %Y "$tmp" 2>/dev/null || echo 0)" ]; then # Only dump to stdout if file was saved while in $EDITOR and its mtime was updated, or the force pipe flag was set
-			cat "$tmp"
-			exit 0
-		else
-			echo "$(basename "$0") FATAL: ${VISUAL:-${EDITOR:-vi}} exited without saving" >&2
-			exit 1
-		fi
-	else
-		echo "$(basename "$0") FATAL: failed to create temporary file" >&2
-		exit 1
-	fi
+  template="${1}"
+  pipe_without_save="${2}"
+  if tmp=$(mktemp -q -p "${TMPDIR:-/tmp}" "${template}"); then # Create a temp file to act as a buffer for $EDITOR with adequate randomness to avoid race condition attacks, using user template if provided
+    trap 'rm -rf "${tmp}"' ERR EXIT HUP INT TERM               # Removes the temp file when execution finishes, except on receipt of SIGKILL
+    if [[ ! -t 0 ]]; then                                      # If connected to stdin, dump it to the temp file
+      cat >"${tmp}"
+    fi
+    mtime=$(stat -c %Y "${tmp}" 2>/dev/null || echo 0)                                                                # Tracks file mtime before $EDITOR is invoked
+    ${VISUAL:-${EDITOR:-vi}} "${tmp}" </dev/tty >/dev/tty || exit $?                                                  # Invokes $EDITOR with stdio connected
+    if [[ "${pipe_without_save}" -eq 1 ]] || [[ "${mtime}" != "$(stat -c %Y "${tmp}" 2>/dev/null || echo 0)" ]]; then # Only dump to stdout if file was saved while in $EDITOR and its mtime was updated, or the force pipe flag was set
+      cat "${tmp}"
+      exit 0
+    else
+      echo "$(basename "${0}") FATAL: ${VISUAL:-${EDITOR:-vi}} exited without saving" >&2
+      exit 1
+    fi
+  else
+    echo "$(basename "${0}") FATAL: failed to create temporary file" >&2
+    exit 1
+  fi
 }
 
-template="$(basename "$0").XXXXXXXXXXXXXXXX" # Default template used when no user-provided template is present
-pipe_without_save=0                          # By default, nvipe emits an error if the user closes the temporary file without saving.
+template="$(basename "${0}").XXXXXXXXXXXXXXXX" # Default template used when no user-provided template is present
+pipe_without_save=0                            # By default, nvipe emits an error if the user closes the temporary file without saving.
 
 if ! OPTS=$(getopt -o hvt:p --long help,version,template:,pipe-without-save -- "$@"); then
-	echo "$(basename "$0") FATAL: error during argument parsing." >&2
-	exit 1
+  echo "$(basename "${0}") FATAL: error during argument parsing." >&2
+  exit 1
 fi
 
-eval set -- "$OPTS"
+eval set -- "${OPTS}"
 
 while true; do
-	case "$1" in
-	-h | --help)
-		usage
-		shift
-		exit 0
-		;;
-	-v | --version)
-		version
-		shift
-		exit 0
-		;;
-	-t | --template)
-		template="$2"
-		shift 2
-		;;
-	-p | --pipe-without-save)
-		shift
-		pipe_without_save=1
-		;;
-	--)
-		shift
-		break
-		;;
-	*)
-		cat <<EOF >&2
+  case "${1}" in
+  -h | --help)
+    usage
+    shift
+    exit 0
+    ;;
+  -v | --version)
+    version
+    shift
+    exit 0
+    ;;
+  -t | --template)
+    template="${2}"
+    shift 2
+    ;;
+  -p | --pipe-without-save)
+    shift
+    pipe_without_save=1
+    ;;
+  --)
+    shift
+    break
+    ;;
+  *)
+    cat <<EOF >&2
 $(basename "$0"): invalid option -- '${1}'
-Try '$(basename "$0") --help' for more information.
+Try '$(basename "${0}") --help' for more information.
 EOF
-		exit 1
-		;;
-	esac
+    exit 1
+    ;;
+  esac
 done
-main "$template" "$pipe_without_save"
+main "${template}" "${pipe_without_save}"
 
 # vim: set filetype=bash:
